DROP TABLE IF EXISTS GARMENTS;

DROP TABLE IF EXISTS GARMENT_TYPES;

CREATE TABLE GARMENTS (
	GARMENT_ID SERIAL PRIMARY KEY,
	USER_ID INT,
	GARMENT_NAME TEXT,
	GARMENT_TYPE_ID NUMERIC,
	GARMENT_COLOR_ID NUMERIC,
	GARMENT_FORMALITY_ID NUMERIC,
	GARMENT_IMAGE_URL TEXT NOT NULL
);

CREATE TABLE GARMENT_TYPES (
	TYPE_ID NUMERIC REFERENCES GARMENTS (GARMENT_TYPE_ID),
	TYPE_NAME TEXT
);

INSERT INTO
	GARMENTS
VALUES
	(1, 'shirt1', 2, 2, 'shirt1.jpg');

INSERT INTO
	GARMENT_TYPES
VALUES
	(1, 'Bottoms'),
	(2, 'Tops'),
	(3, 'Footwear'),
	(4, 'Headwear'),
	(5, 'Accessories');

SELECT
	*
FROM
	GARMENTS;